package com.example.im2calories;

public class ModelClasses {
    public static String[] MODEL_CLASSES = new String[]{
            "rice",
            "chicken-'n'-egg on rice",
            "beef curry",
            "sushi",
            "chicken rice",
            "fried rice",
            "toast",
            "croissant",
            "roll bread",
            "raisin bread",
            "hamburger",
            "pizza",
            "sandwiches",
            "spaghetti",
            "vegetable tempura",
            "sausage",
            "omelet",
            "stew",
            "fried fish",
            "grilled salmon",
            "sweet and sour pork",
            "tempura",
            "fried chicken",
            "steak",
            "egg sunny-side up",
            "roast chicken",
            "fried shrimp",
            "potato salad",
            "green salad",
            "pizza toast",
            "hot dog",
            "french fries",
            "mixed rice",
            "green curry",
            "paella",
            "pancake",
            "crape",
            "tiramisu",
            "waffle",
            "shortcake",
            "mushroom risotto",
            "french toast",
            "minestrone",
            "chicken nugget",
            "french bread",
            "bagel",
            "scone",
            "tortilla",
            "tacos",
            "nachos",
            "meat loaf",
            "scrambled egg",
            "lasagna",
            "Caesar salad",
            "oatmeal",
            "muffin",
            "popcorn",
            "doughnut",
            "apple pie",
            "lamb kebabs",
            "roast duck",
            "hot pot",
            "pork belly",
            "custard tart",
            "stir-fried mixed vegetables",
            "Pork with lemon",
            "Deep Fried Chicken Wing",
            "Crispy Noodles",
            "Fried spring rolls",
            "Steamed rice roll",
            "brownie",
            "churro",
            "chow mein",
            "kung pao chicken",
            "baked salmon"
    };
}
